name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@2013ae6be9be69120f0b79aa67d97ac930c8f463

